---
- include_vars: config.yml

## NOTE: There are many ways to let Ansible know what cluster/subcluster you are deploying
## here for example we are using "ec2_instance_facts" module to get AWS EC2 tags
# # Collect EC2 tags and set facts
# - local_action:
#     module: ec2_instance_facts
#     filters:
#       "tag:stack_server_type": "{{cluster}}:valkeydb"
#   become: false
## but for demo these values simply hardcoded
- set_fact: cluster="testcluster1"
## here we assume that hostname is like valkeydb-mysubcluster1.testcluster.example.com
- set_fact:
    subcluster: "{{ansible_hostname|regex_replace('\\d+$', '')}}"
#

# Setup third-party tools for debugging purpose
- name: Install redis-cli and docker
  apt:
    update_cache: yes
    pkg:
      - redis-tools
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip

# Special user to identify traffic from sentinel containers and direct it over haproxy
# This adds haproxy to the monitoring chain and failover will be triggered in a case when haproxy on master went down
- user:
    name: sentinel
    comment: "Used to run Valkey Sentinel containers"
    uid: 64446
    shell: /usr/sbin/nologin
    group: nogroup
    create_home: no

- name: Copy valkey get-master script
  copy: src=../../../scripts/{{item}} dest=/opt/cent/bin/ mode=0755
  with_items:
    - common_redis.py
    - redis-get-master.py

- name: Docker python lib
  pip:
    name: ['docker', 'redis']
    executable: pip3

# Disable Transparent Huge Pages
- name: Inject kernel.mm.transparent_hugepage
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled && touch {{ansible_env.HOME}}/.kernel.mm.transparent_hugepage.never"
  args:
    creates: "{{ansible_env.HOME}}/.kernel.mm.transparent_hugepage.never"

- name: Ensure auditing for processes that start prior to auditd is enabled 1/2 (configure grub)
  replace:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 transparent_hugepage=never"'
  register: grub

- name: Ensure auditing for processes that start prior to auditd is enabled 2/2 (update initrd image)
  shell: update-grub
  when: grub.changed

# Add reserved ports we use to the ephemeral range
- name: Reserve tcp ports in ephemeral port range
  sysctl: >
    name=net.ipv4.ip_local_reserved_ports
    value="36379-36479,46379-46479,56379-56479"
    state=present
    ignoreerrors=yes

# Enable vm.overcommit_memory, recommended by Valkey
- name: Enable vm.overcommit_memory
  sysctl: >
    name=vm.overcommit_memory
    value=1
    state=present
    ignoreerrors=yes

# Increase "net/core" subsys registered per network namespace
- name: Increase net.core.somaxconn
  sysctl: >
    name=net.core.somaxconn
    value=65535
    state=present
    ignoreerrors=yes

# Setup Valkey
- name: Pull docker images
  command: docker pull {{item}}
  with_items:
    - valkey/valkey:{{valkey_version}}
    - haproxy:{{haproxy_version}}
  register: docker_pull
  changed_when: '"Downloaded newer image" in docker_pull.stdout'

# Setup list of services per subcluster
- set_fact: servicelist={{services[cluster][subcluster]}}
- set_fact:
    servicelist:
      - key: "{{db_var}}"
        value: "{{services[cluster][subcluster][db_var]}}"
  when: db_var is defined

- set_fact: servicelist={{servicelist|items2dict}}
  when: db_var is defined

- name: Iterate over services inside the subcluster
  include_tasks: service.yml
  with_dict:
    - "{{servicelist}}"
  loop_control:
    loop_var: service_item
  vars:
    service: "{{service_item.key}}"
